### ISSUE TITLE
Is this library available for Cloudflare Workers?

### ISSUE THREAD

**Issue by CatAnonymous** [fingerprintjs/BotD#129]
Is there any way to run it on cf workers environment let me know. Thankyou!

**Comment by xnerhu** [comment]
cc @Finesse

**Comment by Finesse** [comment]
You can't run the BotD code on a CloudFlare worker directly because it needs browser APIs to work. But you can make a worker inject the BotD JS script into the HTML code. An example strategy:

1. Make the worker stand between the client side and your website. The worker must handle requests to and responses from your website.
2. If a response is an HTML page, add `<script>` tags to it. The tags should download and execute BotD, and inject the result into HTML forms that you want to protect as `<input type="hidden" ... >` tags.
3. When the worker handles a request to a protected form, it should check the input value, and block the request if necessary.
