### ISSUE TITLE
When no token is provided an error is returned into `then` callback.

### ISSUE THREAD

**Issue by Valve** [fingerprintjs/botd#4]
All errors should be handled in `catch` block instead. AFAIK, `then` should be called for happy paths only.
@Finesse can confirm that.

**Comment by Valve** [comment]
@Finesse in fpjs-pro, if I don't provide a token, will the error be provided in `.then` or in `.catch`?

**Comment by Finesse** [comment]
@Valve In `.catch`. Examples:

```js
FingerprintJS.load({ token: '' }).catch((error) => {
  // The missing token error will be here
})
```

```js
try {
  await FingerprintJS.load({ token: '' })
} catch (error) {
  // The missing token error will be here
}
```

**Comment by Valve** [comment]
Yes, that was my point. In botd the catch will not be called, and the `.then` will have a special response, which is an error. 
I think it is incorrect.

**Comment by Finesse** [comment]
@Valve It's controversial, but I think most of developers will agree that all errors must be thrown.

The opposite point is that only unexpected errors must be thrown. I don't like it because expected and unexpected errors can be distinguished using the `name` attribute and it's more convenient to handle all successful cases in `then` and failed cases in `catch`.

**Comment by Romchela** [comment]
Done
